# Web Scraping Project – AmbitionBox

##  Step 1: Import Libraries

In [7]:
import pandas as pd
import requests
from bs4 import BeautifulSoup

## Step 2: Fetch Webpage

In [8]:
headers= {'User-Agent':'Mozilla/5.0 (Windows NT 6.3; Win 64 ; x64) Apple WeKit /537.36(KHTML , like Gecko) Chrome/80.0.3987.162 Safari/537.36'} 
webpage=requests.get("https://www.ambitionbox.com/list-of-companies?page=1",headers=headers).text

## Step 3: Parse HTML

In [9]:
soup = BeautifulSoup(webpage,'lxml')

## Step 4: Extract Data

In [ ]:
company = soup.find_all('div', class_='companyCardWrapper')
name=[]
rating=[]
review=[]
salaries=[]
interviews=[]
jobs=[]
benefits=[]


for i in company:
    name.append(i.find('h2').text.strip())
    rating.append(i.find('div', class_="rating_text").text.strip())
    review.append(i.find_all('span',class_='companyCardWrapper__ActionCount')[0].text.strip())
    salaries.append(i.find_all('span',class_='companyCardWrapper__ActionCount')[1].text.strip())
    interviews.append(i.find_all('span',class_='companyCardWrapper__ActionCount')[2].text.strip())
    jobs.append(i.find_all('span',class_='companyCardWrapper__ActionCount')[3].text.strip())
    benefits.append(i.find_all('span',class_='companyCardWrapper__ActionCount')[4].text.strip())
    

d={'name':name, 'rating':rating,'review':review,'salaries':salaries,'interviews':interviews,'jobs':jobs,'benefits':benefits}    

df=pd.DataFrame(d)
df

                      name rating review salaries interviews   jobs benefits
0                      TCS    3.3   1.1L      10L      11.8k   3.7k    10.6k
1                Accenture    3.7  72.8k     6.6L       9.3k  24.4k     6.7k
2                    Wipro    3.6  64.6k     4.8L       6.8k    376     4.6k
3                Cognizant    3.7  60.9k       6L       6.4k    479     5.5k
4                Capgemini    3.7  52.6k     4.8L       5.5k   2.1k     3.7k
5                HDFC Bank    3.8  51.7k     1.5L         3k    327     3.2k
6                  Infosys    3.5  48.3k     5.2L       8.4k     3k     4.8k
7               ICICI Bank    4.0  45.5k     1.5L       2.9k     14     3.7k
8                  HCLTech    3.4  45.5k     3.9L       4.5k    241     3.8k
9            Tech Mahindra    3.4    43k     2.8L       4.5k    617     3.4k
10                 Genpact    3.6  41.7k     2.3L       3.9k    920     3.5k
11                      TP    3.8  37.8k    97.8k       2.2k   1.2k     1.8k
12                     Jio    4.4  33.5k      62k       4.4k     --     2.5k
13               Axis Bank    3.6  32.8k       1L       1.9k    193     2.1k
14  Concentrix Corporation    3.6    32k     1.3L         2k     37     3.1k
15                  Amazon    3.9  31.3k     1.5L       5.9k   2.3k     3.6k
16         Reliance Retail    3.9  27.2k    77.2k       1.9k    109     1.8k
17              iEnergizer    4.6  27.2k    24.5k       1.4k     73      430
18             LTIMindtree    3.6  26.2k       2L       3.4k    416      777
19                     IBM    3.9  25.6k     2.2L       2.6k   2.6k     2.6k

## Step 5: Scrape Multiple Pages

In [12]:
final=pd.DataFrame()

for j in range(1,3):
    url= "https://www.ambitionbox.com/list-of-companies?page={}".format(j)

    headers= {'User-Agent':'Mozilla/5.0 (Windows NT 6.3; Win 64 ; x64) Apple WeKit /537.36(KHTML , like Gecko) Chrome/80.0.3987.162 Safari/537.36'} 
    webpage=requests.get(url,headers=headers).text

    soup = BeautifulSoup(webpage,'lxml')

    company = soup.find_all('div', class_='companyCardWrapper')
    
    name=[]
    rating=[]
    review=[]
    salaries=[]
    interviews=[]
    jobs=[]
    benefits=[]


    for i in company:
        try:
            name.append(i.find('h2').text.strip())
        except:
            rating.append(np.nan)
        
        try:
            rating.append(i.find('div', class_="rating_text").text.strip())
        except:
            rating.append(np.nan)
   
        try:
            review.append(i.find_all('span',class_='companyCardWrapper__ActionCount')[0].text.strip())
        except:
            rating.append(np.nan)
   
        try:
            salaries.append(i.find_all('span',class_='companyCardWrapper__ActionCount')[1].text.strip())
        except:
            rating.append(np.nan)

        try:
            interviews.append(i.find_all('span',class_='companyCardWrapper__ActionCount')[2].text.strip())
        except:
            rating.append(np.nan)
        
        try:
            jobs.append(i.find_all('span',class_='companyCardWrapper__ActionCount')[3].text.strip())
        except:
            rating.append(np.nan)
        try:
            benefits.append(i.find_all('span',class_='companyCardWrapper__ActionCount')[4].text.strip())
        except:
            rating.append(np.nan)

    d={'name':name, 'rating':rating,'review':review,'salaries':salaries,'interviews':interviews,'jobs':jobs,'benefits':benefits}    

    df=pd.DataFrame(d)
    df
    final = pd.concat([final,df],ignore_index=True)

## Final Output

In [16]:
final.shape
final.head()

        name rating review salaries interviews   jobs benefits
0        TCS    3.3   1.1L      10L      11.8k   3.7k    10.6k
1  Accenture    3.7  72.8k     6.6L       9.3k  24.4k     6.7k
2      Wipro    3.6  64.6k     4.8L       6.8k    376     4.6k
3  Cognizant    3.7  60.9k       6L       6.4k    479     5.5k
4  Capgemini    3.7  52.6k     4.8L       5.5k   2.1k     3.7k

In [15]:
final.to_csv("ambitionbox_data.csv", index=False)

## Conclusion

- Successfully scraped company data from AmbitionBox  
- Extracted 4000+ records  
- Converted unstructured data into structured format  
- Ready for data analysis and visualization